package duke.util;

/**
 * Represents the user interaction function of the program.
 */
public class Ui {

    private static final String intro = "Hello! I'm Duke! What can I do for you?";
    private static final String indent = "    ";
    private String response;
    private String errorMsg;

    /**
     * Returns the default indentation of output.
     *
     * @return Indentation of four spaces.
     */
    public String showIndent() {
        return indent;
    }

    /**
     * Returns the welcome message when user first runs program.
     */
    public static String showWelcome() {
        return Ui.intro;
    }

    /**
     * Returns error message.
     *
     * @param message The error message.
     */
    public String showError(String message) {
        errorMsg = message;
        return message;
    }

    /**
     * Sets the current response generated by Duke based on user input.
     *
     * @param message The output to be shown.
     */
    public void setResponse(String message) {
        response = message;
    }

    /**
     * Returns the latest response generated by Duke based on user input.
     *
     * @return Response message.
     */
    public String showResponse() {
        return response;
    }
}
