package duke.parser;

import duke.command.AddCommand;
import duke.command.Commands;
import duke.command.DeleteCommand;
import duke.command.ExitCommand;
import duke.command.FindCommand;
import duke.command.HelpCommand;
import duke.command.ListCommand;
import duke.command.MarkCommand;
import duke.command.UnmarkCommand;

/**
 * Represents a parser that makes sense of the command provided by the user.
 * A ParserTest corresponds to a parsing tool whose method can be
 * used universally to make sense of a user input.
 */
public class Parser {

    /**
     * Trim the input of the user.
     *
     * @param input Input to be trimmed.
     * @return Return a trimmed output of the input.
     */
    public static String trim(String input) {
        return input.trim();
    }

    /**
     * Parse a String to its Integer counterpart.
     *
     * @param input Input to be parsed.
     * @return The Integer counterpart of the input.
     */
    public static Integer parseToInt(String input) throws NumberFormatException {
        return Integer.parseInt(input);
    }

    /**
     * A method that abstract away the method of parsing a string array into an integer array.
     *
     * @param input Takes in the String array to be parsed.
     * @return Returns the Integer array parsed from the String.
     */
    public static int[] parseToIntArray(String[] input) {
        int[] parsedArray = new int[input.length];
        if (parsedArray.length < 1) {
            return parsedArray;
        }

        for (int i = 0; i < input.length; i++) {
            parsedArray[i] = Integer.parseInt(input[i].trim());
        }
        return parsedArray;
    }

    /**
     * Convert an input into its zero-based counterpart.
     *
     * @param input The integer to be converted to its zero-based counterpart.
     * @return The zero-based counterpart of the input.
     */
    public static Integer convertBases(Integer input) {
        return input - 1;
    }

    /**
     * Convert all the elements in an array into its zero-indexed counterpart.
     *
     * @param input An integer array seeking to have its bases converted.
     * @return The integer array which is now zero-indexed.
     */
    public static int[] massConvertBases(int[] input) {
        int[] newBaseArray = new int[input.length];
        if (input.length < 1) {
            return newBaseArray;
        }

        for (int i = 0; i < input.length; i++) {
            newBaseArray[i] = input[i] - 1;
        }
        return newBaseArray;
    }

    /**
     * Split a String.
     *
     * @param input The String to be split.
     * @param condition A String keyword to split the input by.
     * @param limit The number of maximum elements to be split.
     * @return A split String array.
     */
    public static String[] splitString(String input, String condition, Integer limit) {
        return input.split(condition, limit);
    }
    /**
     * Returns the command based on the input of the user. If the command is
     * not valid, it returns a <code>HelpCommand</code>, else it returns one
     * that has specific execution instructions that prompt and guide the bot
     * towards specific execution, actions, and behaviours..
     *
     * @param fullCommand The input provided by the user using the CLI.
     * @return the specific command generated by the user input.
     */
    public static Commands parse(String fullCommand) {
        StringBuilder arguments = new StringBuilder("");
        String trimmedCommand = trim(fullCommand);
        String commandWord = trim(splitString(trimmedCommand, " ", 2)[0]);
        if (splitString(trimmedCommand, " ", 2).length > 1) {
            arguments.append(trim(splitString(trimmedCommand, " ", 2)[1]));
        }

        switch (commandWord) {
        //Fallthrough
        case AddCommand.COMMAND_TODO:

        //Fallthrough
        case AddCommand.COMMAND_EVENT:

        //Fallthrough
        case AddCommand.COMMAND_DEADLINE:
            return new AddCommand(commandWord,
                    arguments.toString());

        //Fallthrough
        case ExitCommand.COMMAND_WORDS:
            return new ExitCommand();

        //Fallthrough
        case ListCommand.COMMAND_WORDS:
            return new ListCommand();

        //Fallthrough
        case MarkCommand.COMMAND_WORDS:
            return new MarkCommand(arguments.toString());

        //Fallthrough
        case UnmarkCommand.COMMAND_WORDS:
            return new UnmarkCommand(arguments.toString());

        //Fallthrough
        case DeleteCommand.COMMAND_WORDS:
            return new DeleteCommand(arguments.toString());

        case FindCommand.COMMAND_WORDS:
            return new FindCommand(arguments.toString().split(" ")[0]);

        default:
            return new HelpCommand();
        }

    }
}
