package Alfred.Exceptions;

/**
 * Encapsulates all expected exceptions generated by the Alfred class.
 */
public class AlfredException extends Exception {
    public AlfredException(String errorMessage) {
        super(errorMessage);
    }
}
